### ISSUE TITLE
Pasting URL which contain certain characters does not work OK (brackets)

### ISSUE THREAD

**Issue by bartosz-jarmuz** [denolehov/obsidian-url-into-selection#16]
**Use case:**

Paste links with 'highlight text fragment features', like this one:

**This one works OK:**
https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=Also%20works%20the%20other%20way%20around%2C%20inserts%20text%20into%20a%20selected%20link

**This one does not:**
https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=selected%20link%20(URL)%20by%20command
That's the result:
![image](https://user-images.githubusercontent.com/33833009/115853671-b7407000-a429-11eb-91b4-c6e7ffa6bdd2.png)

I suppose it's the brackets that breaks it.

**Expected behaviour:**

Link with brackets should work OK.

**Comment by AidenLx** [comment]
fixed in [f9f678](https://github.com/denolehov/obsidian-url-into-selection/pull/14/commits/f9f678c98654b233c4f6c4d831371fa5c9a4143e), should work once pr is merged

**Comment by denolehov** [comment]
thanks to @AidenLx, this should no longer be an issue!

**Comment by bartosz-jarmuz** [comment]
Hello,
Thanks a lot for jumping on that so quickly.
I'm afraid it still doesn't work after updating to 1.6. Actually, even the working behaviour is now broken.
  
See the two gifs using the links from the current issue.

![fail1](https://user-images.githubusercontent.com/33833009/116519773-2ad2f900-a8d2-11eb-92d9-50431f830e9b.gif)
![fail2](https://user-images.githubusercontent.com/33833009/116519777-2c042600-a8d2-11eb-991a-ad5864325c7b.gif)

Also that is the raw content I get after pasting (second scenario)

> Test me [https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=selected%20link%20(URL)%20by%20command](https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=selected%20link%20(URL)%20by%20command)[](https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=selected%20link%20(URL)%20by%20command)[again](https://github.com/denolehov/obsidian-url-into-selection#user-content-paste-url-into-selection:~:text=selected%20link%20(URL)%20by%20command)

**Comment by denolehov** [comment]
Hey, I will take a look.

Oh and in the meantime, please restart Obsidian and try testing it again. I know it sounds weird, but I had similar issues where Obsidian didn't unload the plugin after update, so I had _two instances_ of a plugin running at the same time.
